import React, { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Camera, Clock3, Eye, KeyRound, Plus, RadioTower, RefreshCw, ShieldCheck, Video, VideoOff } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { DialogViewport } from '../components/ui/DialogViewport';
import { useToast } from '../components/ui/Toast';
import { useAuth } from '../context/AuthContext';
import { API_URL } from '../data/auth';
import { Camara, crearCamara, crearIntegracionCamara, generarTokenCamara, IntegracionCamara, ProveedorCamara, ResumenCamaras, resumenCamaras } from '../data/camarasApi';

type Tab = 'vivo' | 'actividad' | 'conexiones';

const PROVIDERS: Record<ProveedorCamara, string> = {
  onvif: 'ONVIF / RTSP multimarca', frigate: 'Frigate AI Gateway', hikvision: 'Hikvision / Hik-Connect',
  dahua: 'Dahua / DMSS', reolink: 'Reolink', tuya: 'Tuya / Smart Life', generico: 'Gateway HTTPS genérico',
};

function ago(value?: string | null) {
  if (!value) return 'Sin actividad';
  const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000));
  if (seconds < 60) return `hace ${seconds} s`;
  if (seconds < 3600) return `hace ${Math.floor(seconds / 60)} min`;
  if (seconds < 86400) return `hace ${Math.floor(seconds / 3600)} h`;
  return `hace ${Math.floor(seconds / 86400)} días`;
}

function CameraPlayer({ camera }: { camera: Camara }) {
  if (!camera.reproduccionUrl) return <div className="grid aspect-video place-items-center bg-slate-950 text-center text-slate-400"><div><VideoOff className="mx-auto mb-2" size={30} /><strong className="block text-sm text-white">Esperando gateway de video</strong><span className="mt-1 block max-w-xs text-xs">La cámara está registrada; el vivo se habilita cuando conectemos el NVR o gateway local.</span></div></div>;
  if (camera.protocoloReproduccion === 'jpeg') return <div className="aspect-video bg-slate-950"><img src={camera.reproduccionUrl} alt={`Vista de ${camera.nombre}`} className="h-full w-full object-contain" /></div>;
  if (camera.protocoloReproduccion === 'webrtc') return <div className="grid aspect-video place-items-center bg-slate-950 text-center text-slate-300"><div><RadioTower className="mx-auto mb-2 text-cyan-400" /><strong className="block">Gateway WebRTC configurado</strong><span className="mt-1 block text-xs">La sesión segura se activará mediante el adaptador del gateway.</span></div></div>;
  return <video src={camera.reproduccionUrl} autoPlay muted controls playsInline preload="metadata" className="aspect-video w-full bg-slate-950 object-contain" />;
}

export const Camaras: React.FC = () => {
  const { usuario } = useAuth();
  const { toast } = useToast();
  const [data, setData] = useState<ResumenCamaras | null>(null);
  const [tab, setTab] = useState<Tab>('vivo');
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [connectorOpen, setConnectorOpen] = useState(false);
  const [cameraOpen, setCameraOpen] = useState(false);
  const [endpoint, setEndpoint] = useState<string | null>(null);
  const owner = usuario?.rol === 'admin';
  const editable = owner || usuario?.rol === 'jefatura';
  const load = async (quiet = false) => {
    quiet ? setRefreshing(true) : setLoading(true);
    try { setData(await resumenCamaras()); } catch (error) { toast(error instanceof Error ? error.message : 'No se pudo cargar Cámaras.', 'error'); }
    finally { setLoading(false); setRefreshing(false); }
  };
  useEffect(() => { load(); }, []);
  useEffect(() => { const timer = setInterval(() => load(true), 10_000); return () => clearInterval(timer); }, []);
  const stats = useMemo(() => ({
    online: data?.camaras.filter((camera) => camera.estado === 'en_linea').length ?? 0,
    events: data?.movimientosPorHora.reduce((sum, item) => sum + item.total, 0) ?? 0,
    people: data?.movimientosPorHora.reduce((sum, item) => sum + item.personas, 0) ?? 0,
  }), [data]);

  if (loading || !data) return <div className="space-y-4 p-4 sm:p-6"><div className="h-20 animate-pulse bg-subtle" /><div className="aspect-video animate-pulse bg-subtle" /></div>;
  return <div className="mx-auto max-w-[1600px] space-y-5 p-3 pb-24 sm:p-6 lg:p-8">
    <header className="border-l-4 border-cyan-600 bg-surface p-4 shadow-soft sm:p-5"><div className="flex items-start gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center bg-cyan-700 text-white"><Camera size={22} /></div><div className="min-w-0 flex-1"><p className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-700">ActivaQR Cámaras</p><h1 className="font-display text-xl font-black text-content sm:text-2xl">Video y actividad por empresa</h1><p className="mt-1 text-xs leading-relaxed text-muted">Vivo multimarca, movimientos por hora y eventos combinables con sensores y escenas.</p></div><button onClick={() => load(true)} className="grid h-11 w-11 shrink-0 place-items-center border border-line text-muted" aria-label="Actualizar"><RefreshCw size={17} className={refreshing ? 'animate-spin' : ''} /></button></div></header>

    <div className="grid grid-cols-3 gap-2"><Metric icon={Eye} value={`${stats.online}/${data.camaras.length}`} label="En línea" /><Metric icon={Activity} value={String(stats.events)} label="Eventos 24 h" /><Metric icon={ShieldCheck} value={String(stats.people)} label="Personas 24 h" /></div>

    <nav className="flex snap-x overflow-x-auto border-b border-line [scrollbar-width:none]">{([['vivo', 'Vista en vivo', Video], ['actividad', 'Actividad por hora', BarChart3], ['conexiones', 'Conexiones', RadioTower]] as Array<[Tab, string, React.ElementType]>).map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex min-h-12 shrink-0 items-center gap-2 border-b-2 px-4 text-xs font-black uppercase ${tab === id ? 'border-cyan-600 text-cyan-700' : 'border-transparent text-faint'}`}><Icon size={16} />{label}</button>)}</nav>

    {tab === 'vivo' && <section className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-xl font-black text-content">Mosaico en vivo</h2><p className="text-xs text-muted">Las URLs privadas y contraseñas nunca se entregan al navegador.</p></div>{editable && <button onClick={() => setCameraOpen(true)} disabled={!data.integraciones.length} className="flex h-11 items-center justify-center gap-2 bg-cyan-700 px-4 text-xs font-black uppercase text-white disabled:opacity-40"><Plus size={16} /> Registrar cámara</button>}</div>{data.camaras.length ? <div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{data.camaras.map((camera) => <article key={camera.id} className="overflow-hidden border border-line bg-surface shadow-soft"><CameraPlayer camera={camera} /><div className="flex items-start gap-3 p-4"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${camera.estado === 'en_linea' ? 'bg-emerald-500' : 'bg-slate-400'}`} /><div className="min-w-0 flex-1"><h3 className="break-words font-black text-content">{camera.nombre}</h3><p className="mt-1 text-xs text-muted">{camera.ubicacion || 'Ubicación pendiente'} · {camera.integracion.nombre}</p><p className="mt-1 text-[10px] uppercase tracking-wide text-faint">Movimiento {ago(camera.ultimoMovimientoEn)}</p></div><span className="shrink-0 text-[9px] font-black uppercase text-faint">{camera.estado.replace('_', ' ')}</span></div></article>)}</div> : <Empty title="Listo para conectar las cámaras" text="Todavía no hay acceso al NVR. Podés crear el conector y dejar preparado el inventario; el vivo se habilitará cuando tengamos el gateway local o la nube del fabricante." action={owner ? () => setTab('conexiones') : undefined} />}</section>}

    {tab === 'actividad' && <section className="space-y-5"><div><h2 className="font-display text-xl font-black text-content">Detecciones por hora</h2><p className="mt-1 text-xs text-muted">Últimas 24 horas. Separa movimiento general, personas y vehículos.</p></div><div className="h-72 border border-line bg-surface p-3 shadow-soft sm:p-5"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.movimientosPorHora.map((item) => ({ ...item, hora: new Date(item.inicio).toLocaleTimeString('es-AR', { hour: '2-digit', minute: '2-digit' }) }))}><CartesianGrid strokeDasharray="3 3" opacity={0.2} /><XAxis dataKey="hora" tick={{ fontSize: 9 }} minTickGap={28} /><YAxis allowDecimals={false} tick={{ fontSize: 10 }} width={28} /><Tooltip /><Bar dataKey="movimiento" name="Movimiento" stackId="eventos" fill="#64748b" /><Bar dataKey="personas" name="Personas" stackId="eventos" fill="#0891b2" /><Bar dataKey="vehiculos" name="Vehículos" stackId="eventos" fill="#f59e0b" /></BarChart></ResponsiveContainer></div><div><h2 className="font-display text-xl font-black text-content">Eventos recientes</h2><div className="mt-3 space-y-2">{data.eventos.map((event) => <article key={event.id} className="flex gap-3 border border-line bg-surface p-3 sm:p-4"><div className={`grid h-10 w-10 shrink-0 place-items-center ${event.tipo === 'persona' ? 'bg-cyan-500/10 text-cyan-700' : event.tipo === 'desconexion' || event.tipo === 'manipulacion' ? 'bg-red-500/10 text-red-600' : 'bg-subtle text-muted'}`}>{event.tipo === 'desconexion' ? <VideoOff size={18} /> : <Activity size={18} />}</div><div className="min-w-0 flex-1"><strong className="block break-words text-content">{event.camara.nombre} · {event.tipo}</strong><p className="mt-1 text-xs text-muted">{event.zona ? `Zona ${event.zona} · ` : ''}{new Date(event.iniciadoEn).toLocaleString('es-AR')}{event.confianza != null ? ` · ${Math.round(event.confianza * 100)}%` : ''}</p></div></article>)}{!data.eventos.length && <Empty title="Sin eventos todavía" text="Los movimientos aparecerán cuando un gateway ONVIF, Frigate o del fabricante envíe la primera detección." />}</div></div></section>}

    {tab === 'conexiones' && <section className="space-y-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-display text-xl font-black text-content">Conectores de video</h2><p className="text-xs text-muted">Cada conector y sus cámaras pertenecen solamente a este tenant.</p></div>{owner && <button onClick={() => setConnectorOpen(true)} className="flex h-11 items-center justify-center gap-2 bg-cyan-700 px-4 text-xs font-black uppercase text-white"><Plus size={16} /> Nuevo conector</button>}</div><div className="grid gap-3 lg:grid-cols-2">{data.integraciones.map((item) => <article key={item.id} className="border border-line bg-surface p-4 shadow-soft"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center bg-cyan-500/10 text-cyan-700"><RadioTower size={18} /></div><div className="min-w-0 flex-1"><h3 className="font-black text-content">{item.nombre}</h3><p className="mt-1 text-xs text-muted">{PROVIDERS[item.proveedor]}</p></div><span className="text-[9px] font-black uppercase text-faint">{item.estado}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs"><div className="border border-line p-3"><span className="block text-faint">Último evento</span><strong className="text-content">{ago(item.ultimoEventoEn)}</strong></div><div className="border border-line p-3"><span className="block text-faint">Token</span><strong className="text-content">{item.webhookTokenHint ? `···${item.webhookTokenHint}` : 'Pendiente'}</strong></div></div>{owner && <button onClick={async () => { try { const result = await generarTokenCamara(item.id); setEndpoint(`${(API_URL ?? '').replace(/\/api\/?$/, '')}${result.endpoint}`); await load(true); } catch (error) { toast(error instanceof Error ? error.message : 'No se pudo generar el endpoint.', 'error'); } }} className="mt-3 flex min-h-11 w-full items-center justify-center gap-2 border border-line px-3 text-xs font-black uppercase text-content"><KeyRound size={14} /> {item.webhookTokenHint ? 'Rotar endpoint' : 'Generar endpoint de eventos'}</button>}</article>)}</div>{!data.integraciones.length && <Empty title="Sin conexión de cámaras" text="Creá un conector ahora. Cuando identifiquemos el NVR elegiremos ONVIF, fabricante o Frigate sin rehacer el panel." action={owner ? () => setConnectorOpen(true) : undefined} />}</section>}

    {connectorOpen && <ConnectorModal onClose={() => setConnectorOpen(false)} onDone={async () => { setConnectorOpen(false); await load(true); }} toast={toast} />}
    {cameraOpen && <CameraModal integrations={data.integraciones} onClose={() => setCameraOpen(false)} onDone={async () => { setCameraOpen(false); await load(true); }} toast={toast} />}
    {endpoint && <Modal title="Endpoint seguro de eventos" onClose={() => setEndpoint(null)}><p className="text-sm leading-relaxed text-muted">Copialo ahora en el gateway. Al rotarlo, el anterior deja de funcionar.</p><code className="mt-4 block break-all border border-line bg-subtle p-3 text-xs text-content">{endpoint}</code><button onClick={() => navigator.clipboard.writeText(endpoint).then(() => toast('Endpoint copiado.', 'success'))} className="mt-4 h-11 w-full bg-cyan-700 text-xs font-black uppercase text-white">Copiar endpoint</button></Modal>}
  </div>;
};

function Metric({ icon: Icon, value, label }: { icon: React.ElementType; value: string; label: string }) { return <div className="min-w-0 border border-line bg-surface p-3 shadow-soft"><Icon size={16} className="mb-2 text-cyan-700" /><strong className="block text-xl font-black text-content sm:text-2xl">{value}</strong><span className="block truncate text-[9px] font-black uppercase tracking-wide text-faint sm:text-[10px]">{label}</span></div>; }
function Empty({ title, text, action }: { title: string; text: string; action?: () => void }) { return <div className="border border-dashed border-line-strong bg-subtle p-7 text-center"><Video size={30} className="mx-auto mb-3 text-faint" /><h3 className="font-display text-lg font-black text-content">{title}</h3><p className="mx-auto mt-1 max-w-xl text-sm leading-relaxed text-muted">{text}</p>{action && <button onClick={action} className="mt-4 min-h-11 bg-slate-900 px-4 text-xs font-black uppercase text-white">Comenzar conexión</button>}</div>; }
const input = 'mt-1 h-11 w-full border border-line bg-surface px-3 text-sm font-normal normal-case tracking-normal outline-none focus:border-cyan-600';
function Field({ label, children, hint }: { label: string; children: React.ReactNode; hint?: string }) { return <label className="block text-xs font-black uppercase tracking-wider text-muted">{label}{children}{hint && <span className="mt-1 block text-[11px] font-normal normal-case tracking-normal text-faint">{hint}</span>}</label>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <DialogViewport className="z-50 flex items-end justify-center bg-slate-950/60 sm:items-center sm:p-4" onEscape={onClose}><div className="max-h-[94dvh] w-full max-w-xl overflow-y-auto border-x border-t border-line bg-surface p-4 pb-[calc(1rem+env(safe-area-inset-bottom))] shadow-2xl sm:border sm:p-5"><div className="mb-4 flex items-start justify-between gap-3"><h2 className="font-display text-xl font-black text-content">{title}</h2><button onClick={onClose} className="min-h-11 px-2 text-xs font-black uppercase text-faint">Cerrar</button></div>{children}</div></DialogViewport>; }

function ConnectorModal({ onClose, onDone, toast }: { onClose: () => void; onDone: () => void; toast: ReturnType<typeof useToast>['toast'] }) {
  const [name, setName] = useState('Cámaras Escuela Nueva Austral'); const [provider, setProvider] = useState<ProveedorCamara>('onvif'); const [saving, setSaving] = useState(false);
  return <Modal title="Nuevo conector de cámaras" onClose={onClose}><form className="space-y-4" onSubmit={async (event) => { event.preventDefault(); setSaving(true); try { await crearIntegracionCamara({ nombre: name, proveedor: provider }); toast('Conector preparado. Ya podés generar su endpoint.', 'success'); onDone(); } catch (error) { toast(error instanceof Error ? error.message : 'No se pudo crear.', 'error'); setSaving(false); } }}><Field label="Nombre"><input required value={name} onChange={(event) => setName(event.target.value)} className={input} /></Field><Field label="Sistema"><select value={provider} onChange={(event) => setProvider(event.target.value as ProveedorCamara)} className={input}>{Object.entries(PROVIDERS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><div className="border border-cyan-500/30 bg-cyan-500/5 p-3 text-xs leading-relaxed text-muted">ONVIF es la opción inicial recomendada cuando todavía no conocemos la marca del NVR. El conector puede cambiarse o complementarse después.</div><button disabled={saving} className="h-12 w-full bg-cyan-700 text-xs font-black uppercase text-white disabled:opacity-50">{saving ? 'Preparando…' : 'Crear conector'}</button></form></Modal>;
}

function CameraModal({ integrations, onClose, onDone, toast }: { integrations: IntegracionCamara[]; onClose: () => void; onDone: () => void; toast: ReturnType<typeof useToast>['toast'] }) {
  const [form, setForm] = useState({ integracionId: integrations[0]?.id ?? '', nombre: '', identificadorExterno: '', ubicacion: '', modelo: '', reproduccionUrl: '', protocoloReproduccion: '' }); const [saving, setSaving] = useState(false);
  return <Modal title="Registrar cámara" onClose={onClose}><form className="space-y-4" onSubmit={async (event) => { event.preventDefault(); setSaving(true); try { await crearCamara(form); toast('Cámara registrada para este tenant.', 'success'); onDone(); } catch (error) { toast(error instanceof Error ? error.message : 'No se pudo registrar.', 'error'); setSaving(false); } }}><Field label="Conector"><select required value={form.integracionId} onChange={(event) => setForm({ ...form, integracionId: event.target.value })} className={input}>{integrations.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></Field><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="Nombre visible"><input required value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} className={input} placeholder="Ej: Entrada principal" /></Field><Field label="Identificador"><input required value={form.identificadorExterno} onChange={(event) => setForm({ ...form, identificadorExterno: event.target.value })} className={input} placeholder="Ej: cam-entrada" /></Field></div><Field label="Ubicación"><input value={form.ubicacion} onChange={(event) => setForm({ ...form, ubicacion: event.target.value })} className={input} placeholder="Ej: Acceso calle principal" /></Field><Field label="Modelo" hint="Puede quedar pendiente hasta acceder al equipo."><input value={form.modelo} onChange={(event) => setForm({ ...form, modelo: event.target.value })} className={input} /></Field><div className="border border-amber-500/30 bg-amber-500/5 p-3 text-xs text-muted"><strong className="block text-content">Vivo opcional por ahora</strong>No cargues RTSP ni contraseñas. Cuando instalemos el gateway, ActivaQR recibirá una URL HTTPS segura.</div><button disabled={saving} className="h-12 w-full bg-cyan-700 text-xs font-black uppercase text-white disabled:opacity-50">{saving ? 'Guardando…' : 'Registrar cámara'}</button></form></Modal>;
}

